apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ren3.fullname" . }}-data
  labels:
{{ include "ren3.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "10Gi" }}
  storageClassName: {{ .Values.pvc.storageClassName | default "gp2" }}