{{- if index .Values.secrets "ren3-server" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ (index .Values.secrets "ren3-server").secretProviderClass }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ren3.labels" . | nindent 4 }}
spec:
  provider: aws
  secretObjects:
    - secretName: ren3-server-secrets
      type: Opaque
      data:
        {{- range (index .Values.secrets "ren3-server").keys }}
        - objectName: {{ .alias | quote }}
          key: {{ .alias | quote }}
        {{- end }}
  parameters:
    region: ap-southeast-1
    objects: |
      - objectName: {{ (index .Values.secrets "ren3-server").awsSecretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          {{- range (index .Values.secrets "ren3-server").keys }}
          - path: {{ .path | quote }}
            objectAlias: {{ .alias | quote }}
          {{- end }}
{{- end }}
